pipeline:
    0_caloric_scorer:
        weight: 1
        threshold: 500 # in kcal
        protein_cal_per_gram: 4 # kcal
        fat_cal_per_gram: 9 # kcal
        fiber_cal_per_gram: 2 # kcal
    1_fat_scorer:
        weight: 1
        threshold: 50 #in grams
    2_protein_scorer:
        weight: 2
        threshold: 1 #in grams
    3_fiber_scorer:
        weight: 3
        threshold: 1 #in grams